@extends('layouts.app')
@section('title', __('Users & Roles'))
@section('header', __('Users & Roles'))
@section('content')
<form method="GET" class="flex flex-wrap gap-3 mb-4"><label class="field">{{ __('Search') }}<input name="search" value="{{ request('search') }}"></label><button>{{ __('Search') }}</button></form>
@can('users.create')<form method="POST" action="{{ route('users.store') }}" class="panel grid sm:grid-cols-2 gap-3 mb-5">@csrf<label class="field">{{ __('Name') }}<input name="name" required></label><label class="field">{{ __('Email') }}<input name="email" type="email" required></label><label class="field">{{ __('Password') }}<input name="password" type="password" minlength="12" required></label><label class="field">{{ __('Role') }}<select name="role">@foreach($roles as $r)<option value="{{ $r->name }}">{{ $r->name }}</option>@endforeach</select></label><button class="button-primary">{{ __('Create staff') }}</button></form>@endcan
<div class="panel overflow-x-auto"><table class="w-full"><thead><tr><th>{{ __('Name') }}</th><th>{{ __('Email') }}</th><th>{{ __('Role') }}</th><th>{{ __('Status') }}</th><th>{{ __('Actions') }}</th></tr></thead><tbody>@foreach($users as $u)<tr><td>{{ $u->name }}</td><td>{{ $u->email }}</td><td>{{ $u->getRoleNames()->join(', ') }}</td><td>{{ $u->is_active?__('Active'):__('Inactive') }}</td><td>@can('users.update')@if($u->id!==auth()->id())<form method="POST" action="{{ route('users.update',$u) }}" class="flex flex-wrap gap-2">@csrf @method('PUT')<select name="role" aria-label="{{ __('Role') }} {{ $u->name }}">@foreach($roles as $r)<option value="{{ $r->name }}" @selected($u->hasRole($r->name))>{{ $r->name }}</option>@endforeach</select><select name="is_active" aria-label="{{ __('Status') }} {{ $u->name }}"><option value="1" @selected($u->is_active)>{{ __('Active') }}</option><option value="0" @selected(!$u->is_active)>{{ __('Inactive') }}</option></select><button>{{ __('Save') }}</button></form>@endif
@endcan</td></tr>@endforeach</tbody></table>{{ $users->links() }}</div>
@can('roles.update')<h2 class="text-xl font-semibold my-5">{{ __('Role permissions') }}</h2>@foreach($roles->whereNotIn('name',['owner','super-admin']) as $r)<details class="panel mb-3"><summary>{{ $r->name }}</summary><form method="POST" action="{{ route('roles.update',$r) }}" class="mt-3">@csrf @method('PUT')<div class="grid sm:grid-cols-2 lg:grid-cols-3 gap-2">@foreach($permissions as $permission)<label class="flex items-center gap-2"><input type="checkbox" name="permissions[]" value="{{ $permission->name }}" @checked($r->hasPermissionTo($permission))>{{ $permission->name }}</label>@endforeach</div><button class="button-primary mt-4">{{ __('Save permissions') }}</button></form></details>@endforeach
@endcan
@endsection
