@extends('layouts.customer')
@section('title', __('Cart'))
@section('content')
<h1 class="text-2xl font-semibold mb-4">{{ __('Cart') }}</h1><div id="cartItems" class="space-y-3 mb-4"></div><p id="cartTotal" class="text-xl font-semibold mb-4"></p>
<form id="checkoutForm" action="{{ route('customer.checkout') }}" method="POST" class="panel space-y-3 max-w-xl">@csrf
<label class="field">{{ __('Fulfillment') }}<select name="delivery_type"><option value="pickup">{{ __('Pickup') }}</option><option value="delivery">{{ __('Delivery') }}</option></select></label>
<label class="field">{{ __('Shipping address') }}<textarea name="address" maxlength="2000">{{ old('address') }}</textarea></label>
<label class="field">{{ __('Payment Method') }}<select name="payment_method">@foreach(['cash','transfer','ewallet','qr'] as $method)<option value="{{ $method }}">{{ __('status.'.$method) }}</option>@endforeach @if(config('payments.gateway')==='signed-webhook')<option value="online">{{ __('status.online') }}</option>@endif</select></label>
<label class="field">{{ __('Notes') }}<textarea name="notes" maxlength="2000">{{ old('notes') }}</textarea></label>
<p>{{ __('Final total and stock are verified at checkout.') }}</p>@auth<button id="checkoutBtn" class="button-primary">{{ __('Place order') }}</button>@else<a href="{{ route('login') }}" class="button-primary">{{ __('Login to order') }}</a>@endauth
</form><a class="inline-block mt-4" href="{{ route('customer.shop') }}">{{ __('Browse products') }}</a>
@endsection
@push('scripts')<script>
let cart;try{cart=JSON.parse(localStorage.getItem('warbun_cart')||'[]');if(!Array.isArray(cart))cart=[];}catch{cart=[];}
let key=localStorage.getItem('warbun_checkout_key')||crypto.randomUUID();localStorage.setItem('warbun_checkout_key',key);
function refresh(){const list=document.getElementById('cartItems');list.replaceChildren();if(!cart.length){const p=document.createElement('p');p.textContent=@json(__('No items in cart'));list.append(p);}for(const [i,item] of cart.entries()){const row=document.createElement('div');row.className='panel flex flex-wrap gap-3 items-center';const name=document.createElement('strong');name.textContent=item.name;row.append(name);const input=document.createElement('input');input.type='number';input.min='1';input.max='100000';input.value=item.quantity;input.className='w-24';input.setAttribute('aria-label',@json(__('Quantity'))+' '+item.name);input.onchange=()=>{item.quantity=Math.max(1,Math.min(100000,parseInt(input.value)||1));save();};row.append(input);const remove=document.createElement('button');remove.type='button';remove.textContent=@json(__('Remove'));remove.onclick=()=>{cart.splice(i,1);save();};row.append(remove);list.append(row);}const cents=cart.reduce((s,i)=>s+Math.round(Number(i.price)*100)*i.quantity,0);document.getElementById('cartTotal').textContent=@json(__('Subtotal'))+': '+new Intl.NumberFormat(@json(app()->getLocale()==='id'?'id-ID':'en-US'),{style:'currency',currency:'IDR',maximumFractionDigits:2}).format(cents/100);const btn=document.getElementById('checkoutBtn');if(btn)btn.disabled=!cart.length;}
function save(){localStorage.setItem('warbun_cart',JSON.stringify(cart));window.dispatchEvent(new Event('warbun:cartchange'));key=crypto.randomUUID();localStorage.setItem('warbun_checkout_key',key);refresh();}
const form=document.getElementById('checkoutForm');form.addEventListener('change',()=>{key=crypto.randomUUID();localStorage.setItem('warbun_checkout_key',key);});form.addEventListener('submit',e=>{if(!cart.length){e.preventDefault();return;}for(const el of form.querySelectorAll('[data-cart]'))el.remove();const hidden=(name,value)=>{const el=document.createElement('input');el.type='hidden';el.name=name;el.value=value;el.dataset.cart='true';form.append(el);};hidden('request_key',key);for(const [i,item] of cart.entries()){hidden(`items[${i}][product_id]`,item.id);hidden(`items[${i}][quantity]`,item.quantity);}document.getElementById('checkoutBtn').disabled=true;});refresh();
</script>@endpush
